---
- name: Bastion setup
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: bastion setup variables
      include_vars: Variables/vpc_setup

    - name: import vpc setup variable
      include_vars: Variables/vpc_output_vars

    - name: create vpro ec2 key pair
      ec2_key:
        name: bastion_key
        region: "{{region}}"
      register: bastionkey_out

    - name:  Opening the bastionkey_out output in debug mode
      debug:
        var: bastionkey_out

    - name: save private key into file named bastion_key.pem
      copy:
        content: "{{bastionkey_out.key.private_key}}"
        dest: "./bastionhost_key.pem"
        mode: 0600
      when: bastionkey_out.changed

    - name: Create Security group for bastion host
      ec2_group:
        name: bastion_host_SG
        description: Alow port 22 from everywhere and all port within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"  #my IP keeps changing everytime a new sessions starts. So make sure you change the MYIP variable in variable file
      register: BastionSG_out

    - name: creating EC2 instance
      ec2:
        key_name: vpro_key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion Host"
          Project: Vpro-WebApp
          Owner: Ritesh
        exact_count: 1     # this determine the number of EC2 instance we want with the given configuration
        count_tag:
          Name: "Bastion Host"
          Project: Vpro-WebApp
          Owner: Ritesh
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionhost_out


    - name: insert/update bastion security group id "BastionSGid" in Variables/vpc_output_vars
      blockinfile:    #The blockinfile module in Ansible is used to insert or update a block of text in a file. This module is helpful when you want to add or modify a specific section of a configuration file without altering the entire file. It's commonly used for managing configuration files on remote systems.
        path: Variables/vpc_output_vars
        backup: yes
        block: |
          BastionSGid: {{BastionSG_out.group_id}}
