---
- name: setup vprofile application stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    #importing required variable file that will be used in this playbook.
    - name: including variable files
      include_vars: Variables/vpc_setup

    - name: inclucing ami ids for Vpro-tack instances
      include_vars: Variables/vpro-stack-setup

    - name: Including vpc output variables containing subnet, IG and NWG details
      include_vars: Variables/vpc_output_vars

    - name: create vprofilestack ec2 key-pair #creating key pair for instances
      ec2_key:
        name: vpro_key
        region: "{{region}}"
      register: vrprostack_key_out
    - debug:
        var: vrprostack_key_out

    - name: save private key into file into vprostack.pem #saving the keypair in a file for further use
      copy:
        content: "{{vrprostack_key_out.key.private_key}}"
        dest: ./vprostack.pem
        mode: 0600
     # when: vrprostack_key_out.changed

    # Copying the security key pem file to provision-stack directory
    # In provision-stack directory all the playbooks for services like Nginx, MySQL, RabbitMQ etc will be written

    - name: Copy login key to provision-stack directory
      copy:
        src: vprostack.pem
        dest: provision-stack/vprostack.pem
        mode: '0400'

    # Creating Security group for LoadBalancer of VPro app Stack
    - name: Create security group for Load Balancer
      ec2_group:
        name: vpro_ELB_SG
        description: Allow port 88 from everywhere and all port within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vpro_ELBSG_out

    # Creating Security group for EC2 instances of VPro app stack
    - name: Create Secrurity group for EC2 instances of VproStack
      ec2_group:
        name: vpro_EC2_SG
        description: Allow port 88 from everywhere and all port within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no #this no flag will not allow ansible to re-create or override SG if there is no changes to the rule
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vpro_ELBSG_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"

      register: vpro_EC2SG_out

    #Update Security Group with it's own SG Id to enable all the services interact with each other
    - name: Update Security Group with it's own SG Id
      ec2_group:
        name: vpro_EC2_SG
        description: Allow port 88 from everywhere and all port within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no #this no flag will not allow ansible to re-create or override SG if there is no changes to the rule
        rules:
          - proto: all
            group_id: "{{vpro_EC2SG_out.group_id}}"



    #Creating EC2 instances for services like Nginx, RabbitMQ, Nencached, MySQL
    - name: Creating Nginx Web01
      ec2:
        key_name: vpro_key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{nginx_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "web01"
          Project: Vpro
          Owner: Ritesh
        exact_count: 1      #it will not lunch the instance again and again
        count_tag:
          name: "web01"
          Project: Vpro
          Owner: Ritesh
        group_id: "{{vpro_EC2SG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"             #placing the instance in a private subnet
      register: web01_out

  # Creating EC2 instance for Tomcat

    - name: Creating Tomcat App01
      ec2:
        key_name: vpro_key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{tomcat_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "app01"
          Project: Vpro
          Owner: Ritesh
        exact_count: 1      #it will not lunch the instance again and again
        count_tag:
          name: "app01"
          Project: Vpro
          Owner: Ritesh
        group_id: "{{vpro_EC2SG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: app01_out

    # Creating EC2 instance for Memcached Service

    - name: Creating Memcached MC01
      ec2:
        key_name: vpro_key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{memcache_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "mc01"
          Project: Vpro
          Owner: Ritesh
        exact_count: 1      #it will not lunch the instance again and again
        count_tag:
          name: "mc01"
          Project: Vpro
          Owner: Ritesh
        group_id: "{{vpro_EC2SG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: mc01_out

  #Creating EC2 instance for RabbitMQ

    - name: Creating RabbitMQ RMQ01
      ec2:
        key_name: vpro_key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{rabbitMQ_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "rmq01"
          Project: Vpro
          Owner: Ritesh
        exact_count: 1      #it will not lunch the instance again and again
        count_tag:
          name: "rmq01"
          Project: Vpro
          Owner: Ritesh
        group_id: "{{vpro_EC2SG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: rmq01_out

    #Creating Instance for MySQL Database

    - name: Creating MySQL DB01
      ec2:
        key_name: vpro_key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{mysql_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "db01"
          Project: Vpro
          Owner: Ritesh
        exact_count: 1      #it will not lunch the instance again and again
        count_tag:
          name: "db01"
          Project: Vpro
          Owner: Ritesh
        group_id: "{{vpro_EC2SG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: db01_out

    - debug:
        var: db01_out

    # Creating Elastic Load Balancer(ELB)

    - local_action:
        module: ec2_elb_lb
        name: "vpro-ELB"
        region: "{{region}}"
        state: present
        instance_ids:
          - "{{web01_out.tagged_instances[0].id}}"    #Defining the instances that will be attached to this Load Balancer. here Nginx server
        purge_instance_ids: true
        security_group_ids: "{{vpro_ELBSG_out.group_id}}"
        subnets:
          - "{{pubsub1id}}"
          - "{{pubsub2id}}"
          - "{{pubsub3id}}"
        listeners:
          - protocol: http # we can give http, https, ssl, tcp
            load_balancer_port: 80
            instance_port: 80

    # Storing private IPs of Instances in a file and creating Inventory file out of it

    - name: Insert/Update private IPs and name in file provision-stack/group_vars/host_IPs
      blockinfile:
        path: provision-stack/group_vars/host_IPs
        block: |
          web01_ip: {{web01_out.tagged_instances[0].private_ip}}
          app01_ip: {{app01_out.tagged_instances[0].private_ip}}
          rmq01_ip: {{rmq01_out.tagged_instances[0].private_ip}}
          mc01_ip: {{mc01_out.tagged_instances[0].private_ip}}
          db01_ip: {{db01_out.tagged_instances[0].private_ip}}

    

    # Creating Dynamic-Inventory files with the IPs

    - name: Insert/Update Inventory file provision-stack/inventory-vpro
      blockinfile:
        path: provision-stack/inventory-vpro
        block: |
          web01 ansible_host = {{web01_out.tagged_instances[0].private_ip}}
          app01 ansible_host = {{app01_out.tagged_instances[0].private_ip}}
          rmq01 ansible_host = {{rmq01_out.tagged_instances[0].private_ip}}
          mc01 ansible_host = {{mc01_out.tagged_instances[0].private_ip}}
          db01 ansible_host = {{db01_out.tagged_instances[0].private_ip}}
          cntl ansible_host = 172.31.17.80 ansible_connection=local
        
        
          [webserver_group]
          web01
        
          [appserver_group]
          app01
        
          [rmqserver_group]
          rmq01
        
          [mcserver_group]
          mc01
        
          [dbserver_group]
          db01
          
          [control_machine]
          cntl
          
          [stack_inst:children]
          webserver_group
          appserver_group
          rmqserver_group
          mcserver_group
          dbserver_group
          
          [stack_inst:vars]
          ansible_user: ubuntu
          ansible_ssh_private_key_file=loginkey_vprostack.pem
