---
- name: Setup MySQL with accounts db and remote login
  hosts: dbserver_group
  gather_facts: no
  tasks:
    - name: Installing mysql Service and dependancies
      package:
        name: "{{item}}"
        state: present
        update_cache: yes
        cache_valid_time: 86400

      loop:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - python3-mysqldb
        - libmysqlclient-dev
      ignore_errors: yes
      tags:
        - packages

    - name: Start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes
      tags:
        - svc

    - name: creating mysql user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Creating accounts DB
      mysql_db:
        name: "{{dbname}}"
        state: present

    - name: Enable remote login to mysql Service
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regxp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - restart mysql
      tags:
        - conf

  handlers:
    - name: Restart Mysql
      service:
        name: mysql
        state: restarted